<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/loginpagestyle.css">
    <title>Вход</title>
</head>
<body>
<header>
    <div class="header-container">
        <h1>Сервис для проведения тендерных торгов</h1>
        <div class="buttons">
            <a href="/registration" class="btn-register">Регистрация</a>
            <a href="/" class="btn-main">На главную</a>
        </div>
    </div>
</header>

<main>
    <div class="container">
        <h1>Вход</h1>
        <form action="#" method="post">
            <label>Email</label>
            <input type="text" name="email" placeholder="Email" required>

            <label>Пароль</label>
            <input type="password" name="password" placeholder="Пароль" required>

            <button type="submit">Войти</button>
        </form>
    </div>
</main>

<footer>
    <p>АлтГТУ 2024</p>
</footer>
</body>
</html>