<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/loginpagestyle.css">
    <title>Вход</title>
</head>
<body>
<header>
    <div class="header-container">
        <h1>Сервис для проведения тендерных торгов</h1>
        <div class="buttons">
            <a href="/registration" class="btn-register">Регистрация</a>
            <a href="/" class="btn-main">На главную</a>
        </div>
    </div>
</header>

<main>

</main>

<footer>
    <p>АлтГТУ 2024</p>
</footer>
</body>
</html>