<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/mainpagestyle.css">
    <title>Главная страница</title>
</head>
<body>
<header>
    <div class="header-container">
        <h1>Сервис для проведения тендерных торгов</h1>
        <div class="buttons">
            <a href="/registration" class="btn-register">Регистрация</a>
            <a href="#" class="btn-login">Вход</a>
        </div>
    </div>
</header>

<main>
    <div class="main-content">
        <h2>Проводите и участвуйте в тендерных торгах по всей России!</h2>
        <p>Для доступа к платформе <a href="#">войдите</a> или <a href="/registration">зарегистрируйтесь</a>.</p>
    </div>
</main>

<footer>
    <p>АлтГТУ 2024</p>
</footer>
</body>
</html>